import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Getintouch from "../components/Getintouch";
import Main from "../components/Home";
import Navbar from "../components/navbar";
import Projects from "../components/Projects";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Josiah | Student Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Projects />
      <Getintouch />
    </div>
  );
}
